sudo: false
language: python
python:
- '3.5'
- '3.6'
install:
- travis_retry pip install -e .
script:
- py.test tests
deploy:
  provider: pypi
  user: knowak
  password:
    secure: xCKhjT4DsCg73F83cCbA5St1SAP0DOyfzee3SKvHtgQM3M/hrvzVC/wWlbzJGLKGE0mQvsoGwxJ23CtJDfoeYH1f/5xNo7kWNJDqZjOZqT/IibhbxL7DRu2jODyRiSfYDfkYCAETLCfGl62gJ4OSCwAgGPjf/A6soNO7pw27Dxn8dA0h8au6E0kSY92LiR/hdQNdIlV/ceJ2qINhlVJmJ24v6elTcsGLsrmJOS18lVNv6/AlyurQGI8Jf32G35Eq96YKk8bbWUThG99lDBAr9QJ5d8wOy04pGo4lJnvQFqJY0jl+DFng/BHM0gzymerRJEQa3c8+s3Kjn98Hdidn8AQ6J4weBZ4trVIRVvIO5s8BS6NNdZj5Bl2hiczGXuTFDE9P1frUnUpLrIqOQQ0VGsdMKDLKXaPuGQE0IVBurAkSIN223bdkp63JCpNxIlRC7rsHj8Euo8FMKHDNGXqRQ2Frq4dIqCDKbtCMrb8gv3lNiHF0sp+l8rH7BeBqDSUXay99Z/HK/2pIIMVTx3kgq1QXiUWltxBcTkm77EWOPkAFSLE3DyH2vxH91VR1n7c9c7F8nRf08qkYNSmgJxQGoy6SRAibQ+fjFB+c/TjgPgWz/ANL1RoHq71Zo7ToYz4K38cTNfYIhh21wHRzZ5XuSLlAe+4xB/+yTUJsQ1/t2qw=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.5'
    repo: hadroid/hadroid
